### ISSUE TITLE
Some statc files are not served

### ISSUE THREAD

**Issue by asafpm** [colab-chat/colab-server#16]
When requesting `http://localhost/static/bootstrap/js/bootstrap.min.js` the file is returned while requesting `http://localhost/static/bootstrap/js/jquery.min.js` returns a 404 error.

It might be a good idea to anyway give the responsibility of serving static files directly to nginx although it would be nice to find out what is causing this issue.

**Comment by matthew-d-jones** [comment]
Closed by #18
